# Label Encoding

In [7]:
from sklearn.preprocessing import LabelEncoder

items = ['A', 'B', 'C', 'D', 'E', 'B', 'E']

encoder = LabelEncoder()
encoder.fit(items)
labels = encoder.transform(items)
print(labels)
print(encoder.classes_)

[0 1 2 3 4 1 4]
['A' 'B' 'C' 'D' 'E']


In [8]:
print(labels)
print(encoder.inverse_transform(labels))

[0 1 2 3 4 1 4]
['A' 'B' 'C' 'D' 'E' 'B' 'E']


# One Hot Encoding

In [12]:
from sklearn.preprocessing import OneHotEncoder

In [13]:
oh_encoder = OneHotEncoder()
labels = labels.reshape(-1, 1)
oh_encoder.fit(labels)
oh_labels = oh_encoder.transform(labels)
oh_labels.toarray()

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.],
       [0., 1., 0., 0., 0.],
       [0., 0., 0., 0., 1.]])

# get_dummies()

In [10]:
items

['A', 'B', 'C', 'D', 'E', 'B', 'E']

In [9]:
import pandas as pd

df = pd.DataFrame({'item': items})
pd.get_dummies(df)

item_A  item_B  item_C  item_D  item_E
0       1       0       0       0       0
1       0       1       0       0       0
2       0       0       1       0       0
3       0       0       0       1       0
4       0       0       0       0       1
5       0       1       0       0       0
6       0       0       0       0       1